In [1]:
import urllib.parse

domain = "51.91.251.0"
port = 3000
host = f"http://{domain}:{port}"
path = lambda x: urllib.parse.urljoin(host, x)

In [2]:
import requests

user_id = '8ad307f1-c2d2-4e02-8647-2fdf40228105'
name = 'avatar1'
r = requests.post(path(f'avatars/{user_id}/{name}'))
r

In [3]:
name = 'avatar2'
r = requests.post(path(f"avatars/{user_id}/{name}"))
r

In [4]:
r = requests.get(path(f"avatars/{user_id}"))
for avatar in r.json():
    print(avatar['id'], avatar['name'])

30892 avatar1
31622 avatar2

In [6]:
params = {
    "avatar_name": "avatar1",
    "language": "french",
    "city": "paris",
    "date": 2,
    "mobile": 0,
}
r1 = requests.get(path(f"pricing/{user_id}"), params=params)
r1.json()

{'prices': [{'hotel_id': 62, 'price': 86, 'stock': 0},
  {'hotel_id': 882, 'price': 221, 'stock': 0},
  {'hotel_id': 602, 'price': 115, 'stock': 0},
  {'hotel_id': 447, 'price': 136, 'stock': 0},
  {'hotel_id': 645, 'price': 161, 'stock': 0},
  {'hotel_id': 853, 'price': 188, 'stock': 2},
  {'hotel_id': 492, 'price': 117, 'stock': 0},
  {'hotel_id': 970, 'price': 328, 'stock': 3},
  {'hotel_id': 301, 'price': 133, 'stock': 2},
  {'hotel_id': 66, 'price': 186, 'stock': 1},
  {'hotel_id': 797, 'price': 145, 'stock': 0},
  {'hotel_id': 65, 'price': 161, 'stock': 0},
  {'hotel_id': 534, 'price': 399, 'stock': 2},
  {'hotel_id': 306, 'price': 226, 'stock': 3},
  {'hotel_id': 259, 'price': 138, 'stock': 0},
  {'hotel_id': 477, 'price': 84, 'stock': 0},
  {'hotel_id': 342, 'price': 120, 'stock': 0},
  {'hotel_id': 573, 'price': 344, 'stock': 2},
  {'hotel_id': 790, 'price': 454, 'stock': 2},
  {'hotel_id': 738, 'price': 143, 'stock': 1},
  {'hotel_id': 509, 'price': 89, 'stock': 0},
  {'hotel_id': 825, 'price': 188, 'stock': 3},
  {'hotel_id': 942, 'price': 313, 'stock': 1},
  {'hotel_id': 734, 'price': 141, 'stock': 0},
  {'hotel_id': 225, 'price': 191, 'stock': 0},
  {'hotel_id': 634, 'price': 87, 'stock': 0},
  {'hotel_id': 614, 'price': 88, 'stock': 0},
  {'hotel_id': 27, 'price': 354, 'stock': 4},
  {'hotel_id': 227, 'price': 85, 'stock': 0},
  {'hotel_id': 705, 'price': 143, 'stock': 0},
  {'hotel_id': 612, 'price': 226, 'stock': 2},
  {'hotel_id': 571, 'price': 456, 'stock': 1},
  {'hotel_id': 207, 'price': 164, 'stock': 0},
  {'hotel_id': 748, 'price': 318, 'stock': 1},
  {'hotel_id': 980, 'price': 114, 'stock': 0},
  {'hotel_id': 339, 'price': 253, 'stock': 2},
  {'hotel_id': 858, 'price': 300, 'stock': 1},
  {'hotel_id': 308, 'price': 297, 'stock': 1},
  {'hotel_id': 165, 'price': 161, 'stock': 2},
  {'hotel_id': 121, 'price': 83, 'stock': 0},
  {'hotel_id': 851, 'price': 89, 'stock': 0},
  {'hotel_id': 742, 'price': 417, 'stock': 2},
  {'hotel_id': 95, 'price': 454, 'stock': 2},
  {'hotel_id': 785, 'price': 284, 'stock': 1},
  {'hotel_id': 926, 'price': 188, 'stock': 10},
  {'hotel_id': 803, 'price': 363, 'stock': 2},
  {'hotel_id': 132, 'price': 448, 'stock': 2},
  {'hotel_id': 305, 'price': 193, 'stock': 2},
  {'hotel_id': 522, 'price': 196, 'stock': 1},
  {'hotel_id': 975, 'price': 165, 'stock': 4},
  {'hotel_id': 331, 'price': 98, 'stock': 2},
  {'hotel_id': 192, 'price': 119, 'stock': 0},
  {'hotel_id': 756, 'price': 247, 'stock': 2},
  {'hotel_id': 49, 'price': 161, 'stock': 0},
  {'hotel_id': 188, 'price': 85, 'stock': 8},
  {'hotel_id': 257, 'price': 188, 'stock': 0},
  {'hotel_id': 327, 'price': 226, 'stock': 0},
  {'hotel_id': 910, 'price': 88, 'stock': 0},
  {'hotel_id': 69, 'price': 252, 'stock': 46},
  {'hotel_id': 299, 'price': 115, 'stock': 0},
  {'hotel_id': 584, 'price': 461, 'stock': 2},
  {'hotel_id': 736, 'price': 224, 'stock': 1},
  {'hotel_id': 412, 'price': 265, 'stock': 65},
  {'hotel_id': 767, 'price': 188, 'stock': 0},
  {'hotel_id': 41, 'price': 136, 'stock': 2},
  {'hotel_id': 776, 'price': 159, 'stock': 0},
  {'hotel_id': 176, 'price': 86, 'stock': 0},
  {'hotel_id': 397, 'price': 426, 'stock': 2},
  {'hotel_id': 868, 'price': 287, 'stock': 1},
  {'hotel_id': 629, 'price': 87, 'stock': 0},
  {'hotel_id': 949, 'price': 395, 'stock': 2},
  {'hotel_id': 837, 'price': 418, 'stock': 2},
  {'hotel_id': 580, 'price': 141, 'stock': 4},
  {'hotel_id': 863, 'price': 456, 'stock': 2},
  {'hotel_id': 782, 'price': 369, 'stock': 4},
  {'hotel_id': 119, 'price': 315, 'stock': 1},
  {'hotel_id': 357, 'price': 188, 'stock': 2},
  {'hotel_id': 631, 'price': 83, 'stock': 0},
  {'hotel_id': 21, 'price': 86, 'stock': 0},
  {'hotel_id': 946, 'price': 323, 'stock': 1},
  {'hotel_id': 564, 'price': 92, 'stock': 0},
  {'hotel_id': 314, 'price': 117, 'stock': 0},
  {'hotel_id': 885, 'price': 191, 'stock': 2},
  {'hotel_id': 28, 'price': 199, 'stock': 1},
  {'hotel_id': 449, 'price': 221, 'stock': 2},
  {'hotel_id': 992, 'price': 83, 'stock': 0},
  {'hotel_id': 560, 'price': 186, 'stock': 2},
  {'hotel_id': 94, 'price': 250, 'stock': 42},
  {'hotel_id': 379, 'price': 352, 'stock': 2},
  {'hotel_id': 647, 'price': 143, 'stock': 0},
  {'hotel_id': 741, 'price': 190, 'stock': 2},
  {'hotel_id': 248, 'price': 313, 'stock': 1},
  {'hotel_id': 963, 'price': 136, 'stock': 0},
  {'hotel_id': 222, 'price': 340, 'stock': 3},
  {'hotel_id': 14, 'price': 156, 'stock': 0},
  {'hotel_id': 795, 'price': 165, 'stock': 0},
  {'hotel_id': 436, 'price': 247, 'stock': 19},
  {'hotel_id': 842, 'price': 443, 'stock': 2},
  {'hotel_id': 722, 'price': 193, 'stock': 2},
  {'hotel_id': 150, 'price': 226, 'stock': 10},
  {'hotel_id': 216, 'price': 241, 'stock': 4},
  {'hotel_id': 817, 'price': 302, 'stock': 1},
  {'hotel_id': 338, 'price': 196, 'stock': 13},
  {'hotel_id': 558, 'price': 102, 'stock': 0},
  {'hotel_id': 700, 'price': 177, 'stock': 57},
  {'hotel_id': 254, 'price': 164, 'stock': 0},
  {'hotel_id': 889, 'price': 191, 'stock': 0},
  {'hotel_id': 948, 'price': 241, 'stock': 2},
  {'hotel_id': 359, 'price': 141, 'stock': 1},
  {'hotel_id': 115, 'price': 107, 'stock': 18},
  {'hotel_id': 708, 'price': 188, 'stock': 2},
  {'hotel_id': 29, 'price': 318, 'stock': 1},
  {'hotel_id': 866, 'price': 456, 'stock': 2},
  {'hotel_id': 579, 'price': 85, 'stock': 0},
  {'hotel_id': 133, 'price': 158, 'stock': 0},
  {'hotel_id': 419, 'price': 136, 'stock': 2},
  {'hotel_id': 663, 'price': 155, 'stock': 4},
  {'hotel_id': 576, 'price': 226, 'stock': 0},
  {'hotel_id': 595, 'price': 188, 'stock': 0},
  {'hotel_id': 290, 'price': 191, 'stock': 2},
  {'hotel_id': 199, 'price': 228, 'stock': 0},
  {'hotel_id': 903, 'price': 89, 'stock': 0},
  {'hotel_id': 577, 'price': 188, 'stock': 0},
  {'hotel_id': 723, 'price': 86, 'stock': 0},
  {'hotel_id': 640, 'price': 193, 'stock': 0},
  {'hotel_id': 792, 'price': 85, 'stock': 4},
  {'hotel_id': 841, 'price': 87, 'stock': 0},
  {'hotel_id': 937, 'price': 280, 'stock': 1},
  {'hotel_id': 808, 'price': 441, 'stock': 2},
  {'hotel_id': 229, 'price': 221, 'stock': 3},
  {'hotel_id': 123, 'price': 155, 'stock': 1},
  {'hotel_id': 911, 'price': 153, 'stock': 4},
  {'hotel_id': 823, 'price': 313, 'stock': 1},
  {'hotel_id': 684, 'price': 85, 'stock': 0},
  {'hotel_id': 159, 'price': 315, 'stock': 1},
  {'hotel_id': 972, 'price': 100, 'stock': 4},
  {'hotel_id': 884, 'price': 222, 'stock': 0},
  {'hotel_id': 474, 'price': 183, 'stock': 2},
  {'hotel_id': 998, 'price': 224, 'stock': 0},
  {'hotel_id': 274, 'price': 191, 'stock': 0},
  {'hotel_id': 731, 'price': 188, 'stock': 0},
  {'hotel_id': 130, 'price': 315, 'stock': 1},
  {'hotel_id': 484, 'price': 138, 'stock': 2},
  {'hotel_id': 986, 'price': 321, 'stock': 1},
  {'hotel_id': 656, 'price': 150, 'stock': 1},
  {'hotel_id': 599, 'price': 103, 'stock': 14},
  {'hotel_id': 912, 'price': 164, 'stock': 0},
  {'hotel_id': 182, 'price': 162, 'stock': 0},
  {'hotel_id': 735, 'price': 194, 'stock': 1},
  {'hotel_id': 467, 'price': 255, 'stock': 45},
  {'hotel_id': 148, 'price': 114, 'stock': 0},
  {'hotel_id': 24, 'price': 410, 'stock': 2},
  {'hotel_id': 392, 'price': 190, 'stock': 0},
  {'hotel_id': 238, 'price': 159, 'stock': 0},
  {'hotel_id': 617, 'price': 448, 'stock': 2}],
 'request': {'city': 'paris',
  'date': 2,
  'language': 'french',
  'mobile': 0,
  'avatar_id': 30892}}

In [7]:
params = {
    "avatar_name": "avatar2",
    "language": "french",
    "city": "paris",
    "date": 1,
    "mobile": 1,
}
r2 = requests.get(path(f"pricing/{user_id}"), params=params)
r2.json()

{'prices': [{'hotel_id': 858, 'price': 300, 'stock': 1},
  {'hotel_id': 785, 'price': 284, 'stock': 1},
  {'hotel_id': 734, 'price': 141, 'stock': 0},
  {'hotel_id': 222, 'price': 340, 'stock': 2},
  {'hotel_id': 882, 'price': 221, 'stock': 0},
  {'hotel_id': 176, 'price': 86, 'stock': 0},
  {'hotel_id': 992, 'price': 83, 'stock': 0},
  {'hotel_id': 94, 'price': 230, 'stock': 38},
  {'hotel_id': 314, 'price': 117, 'stock': 0},
  {'hotel_id': 150, 'price': 208, 'stock': 10},
  {'hotel_id': 290, 'price': 191, 'stock': 0},
  {'hotel_id': 645, 'price': 161, 'stock': 0},
  {'hotel_id': 738, 'price': 143, 'stock': 0},
  {'hotel_id': 970, 'price': 328, 'stock': 1},
  {'hotel_id': 577, 'price': 188, 'stock': 0},
  {'hotel_id': 573, 'price': 424, 'stock': 1},
  {'hotel_id': 576, 'price': 226, 'stock': 0},
  {'hotel_id': 115, 'price': 98, 'stock': 17},
  {'hotel_id': 776, 'price': 159, 'stock': 0},
  {'hotel_id': 484, 'price': 127, 'stock': 1},
  {'hotel_id': 972, 'price': 92, 'stock': 3},
  {'hotel_id': 436, 'price': 227, 'stock': 15},
  {'hotel_id': 492, 'price': 117, 'stock': 0},
  {'hotel_id': 825, 'price': 173, 'stock': 2},
  {'hotel_id': 617, 'price': 448, 'stock': 1},
  {'hotel_id': 808, 'price': 441, 'stock': 1},
  {'hotel_id': 884, 'price': 222, 'stock': 0},
  {'hotel_id': 509, 'price': 89, 'stock': 0},
  {'hotel_id': 868, 'price': 287, 'stock': 1},
  {'hotel_id': 580, 'price': 129, 'stock': 4},
  {'hotel_id': 614, 'price': 88, 'stock': 0},
  {'hotel_id': 342, 'price': 120, 'stock': 0},
  {'hotel_id': 306, 'price': 226, 'stock': 1},
  {'hotel_id': 866, 'price': 456, 'stock': 1},
  {'hotel_id': 795, 'price': 165, 'stock': 0},
  {'hotel_id': 229, 'price': 204, 'stock': 1},
  {'hotel_id': 133, 'price': 158, 'stock': 0},
  {'hotel_id': 942, 'price': 313, 'stock': 1},
  {'hotel_id': 66, 'price': 186, 'stock': 0},
  {'hotel_id': 308, 'price': 297, 'stock': 1},
  {'hotel_id': 119, 'price': 315, 'stock': 1},
  {'hotel_id': 24, 'price': 410, 'stock': 1},
  {'hotel_id': 656, 'price': 150, 'stock': 0},
  {'hotel_id': 254, 'price': 164, 'stock': 0},
  {'hotel_id': 599, 'price': 95, 'stock': 12},
  {'hotel_id': 227, 'price': 85, 'stock': 0},
  {'hotel_id': 986, 'price': 321, 'stock': 1},
  {'hotel_id': 65, 'price': 161, 'stock': 0},
  {'hotel_id': 121, 'price': 83, 'stock': 0},
  {'hotel_id': 853, 'price': 173, 'stock': 1},
  {'hotel_id': 95, 'price': 454, 'stock': 1},
  {'hotel_id': 359, 'price': 141, 'stock': 0},
  {'hotel_id': 723, 'price': 86, 'stock': 0},
  {'hotel_id': 792, 'price': 78, 'stock': 2},
  {'hotel_id': 305, 'price': 177, 'stock': 1},
  {'hotel_id': 579, 'price': 85, 'stock': 0},
  {'hotel_id': 558, 'price': 102, 'stock': 0},
  {'hotel_id': 742, 'price': 417, 'stock': 1},
  {'hotel_id': 238, 'price': 159, 'stock': 0},
  {'hotel_id': 851, 'price': 89, 'stock': 0},
  {'hotel_id': 937, 'price': 280, 'stock': 1},
  {'hotel_id': 477, 'price': 84, 'stock': 0},
  {'hotel_id': 910, 'price': 88, 'stock': 0},
  {'hotel_id': 192, 'price': 119, 'stock': 0},
  {'hotel_id': 132, 'price': 448, 'stock': 1},
  {'hotel_id': 357, 'price': 188, 'stock': 0},
  {'hotel_id': 327, 'price': 226, 'stock': 0},
  {'hotel_id': 684, 'price': 85, 'stock': 0},
  {'hotel_id': 188, 'price': 78, 'stock': 7},
  {'hotel_id': 447, 'price': 136, 'stock': 0},
  {'hotel_id': 748, 'price': 318, 'stock': 1},
  {'hotel_id': 182, 'price': 162, 'stock': 0},
  {'hotel_id': 69, 'price': 232, 'stock': 42},
  {'hotel_id': 248, 'price': 313, 'stock': 1},
  {'hotel_id': 522, 'price': 196, 'stock': 0},
  {'hotel_id': 842, 'price': 443, 'stock': 1},
  {'hotel_id': 602, 'price': 115, 'stock': 0},
  {'hotel_id': 841, 'price': 87, 'stock': 0},
  {'hotel_id': 837, 'price': 418, 'stock': 1},
  {'hotel_id': 705, 'price': 143, 'stock': 0},
  {'hotel_id': 708, 'price': 173, 'stock': 1},
  {'hotel_id': 790, 'price': 454, 'stock': 1},
  {'hotel_id': 28, 'price': 199, 'stock': 0},
  {'hotel_id': 412, 'price': 244, 'stock': 63},
  {'hotel_id': 612, 'price': 208, 'stock': 1},
  {'hotel_id': 647, 'price': 143, 'stock': 0},
  {'hotel_id': 216, 'price': 241, 'stock': 3},
  {'hotel_id': 629, 'price': 87, 'stock': 0},
  {'hotel_id': 756, 'price': 247, 'stock': 1},
  {'hotel_id': 123, 'price': 155, 'stock': 0},
  {'hotel_id': 912, 'price': 164, 'stock': 0},
  {'hotel_id': 817, 'price': 302, 'stock': 1},
  {'hotel_id': 595, 'price': 188, 'stock': 0},
  {'hotel_id': 49, 'price': 161, 'stock': 0},
  {'hotel_id': 27, 'price': 354, 'stock': 2},
  {'hotel_id': 29, 'price': 318, 'stock': 1},
  {'hotel_id': 949, 'price': 395, 'stock': 1},
  {'hotel_id': 449, 'price': 204, 'stock': 1},
  {'hotel_id': 823, 'price': 313, 'stock': 1},
  {'hotel_id': 663, 'price': 143, 'stock': 3},
  {'hotel_id': 903, 'price': 89, 'stock': 0},
  {'hotel_id': 767, 'price': 188, 'stock': 0},
  {'hotel_id': 963, 'price': 136, 'stock': 0},
  {'hotel_id': 782, 'price': 369, 'stock': 2},
  {'hotel_id': 397, 'price': 426, 'stock': 1},
  {'hotel_id': 885, 'price': 191, 'stock': 1},
  {'hotel_id': 560, 'price': 171, 'stock': 2},
  {'hotel_id': 379, 'price': 430, 'stock': 1},
  {'hotel_id': 148, 'price': 114, 'stock': 0},
  {'hotel_id': 225, 'price': 191, 'stock': 0},
  {'hotel_id': 259, 'price': 138, 'stock': 0},
  {'hotel_id': 339, 'price': 253, 'stock': 1},
  {'hotel_id': 741, 'price': 190, 'stock': 1},
  {'hotel_id': 419, 'price': 125, 'stock': 1},
  {'hotel_id': 199, 'price': 228, 'stock': 0},
  {'hotel_id': 631, 'price': 83, 'stock': 0},
  {'hotel_id': 722, 'price': 193, 'stock': 0},
  {'hotel_id': 21, 'price': 86, 'stock': 0},
  {'hotel_id': 564, 'price': 92, 'stock': 0},
  {'hotel_id': 159, 'price': 315, 'stock': 1},
  {'hotel_id': 257, 'price': 188, 'stock': 0},
  {'hotel_id': 41, 'price': 125, 'stock': 1},
  {'hotel_id': 534, 'price': 399, 'stock': 1},
  {'hotel_id': 274, 'price': 191, 'stock': 0},
  {'hotel_id': 911, 'price': 153, 'stock': 4},
  {'hotel_id': 474, 'price': 183, 'stock': 0},
  {'hotel_id': 803, 'price': 363, 'stock': 1},
  {'hotel_id': 584, 'price': 461, 'stock': 1},
  {'hotel_id': 889, 'price': 191, 'stock': 0},
  {'hotel_id': 14, 'price': 156, 'stock': 0},
  {'hotel_id': 946, 'price': 323, 'stock': 1},
  {'hotel_id': 299, 'price': 115, 'stock': 0},
  {'hotel_id': 62, 'price': 86, 'stock': 0},
  {'hotel_id': 207, 'price': 164, 'stock': 0},
  {'hotel_id': 392, 'price': 190, 'stock': 0},
  {'hotel_id': 975, 'price': 152, 'stock': 3},
  {'hotel_id': 165, 'price': 161, 'stock': 0},
  {'hotel_id': 331, 'price': 90, 'stock': 1},
  {'hotel_id': 130, 'price': 315, 'stock': 1},
  {'hotel_id': 863, 'price': 456, 'stock': 1},
  {'hotel_id': 735, 'price': 194, 'stock': 0},
  {'hotel_id': 467, 'price': 235, 'stock': 43},
  {'hotel_id': 700, 'price': 163, 'stock': 55},
  {'hotel_id': 634, 'price': 87, 'stock': 0},
  {'hotel_id': 926, 'price': 173, 'stock': 8},
  {'hotel_id': 736, 'price': 224, 'stock': 0},
  {'hotel_id': 998, 'price': 224, 'stock': 0},
  {'hotel_id': 980, 'price': 114, 'stock': 0},
  {'hotel_id': 640, 'price': 193, 'stock': 0},
  {'hotel_id': 797, 'price': 145, 'stock': 0},
  {'hotel_id': 301, 'price': 122, 'stock': 1},
  {'hotel_id': 571, 'price': 456, 'stock': 0},
  {'hotel_id': 338, 'price': 180, 'stock': 12},
  {'hotel_id': 731, 'price': 188, 'stock': 0},
  {'hotel_id': 948, 'price': 241, 'stock': 1}],
 'request': {'city': 'paris',
  'date': 1,
  'language': 'french',
  'mobile': 1,
  'avatar_id': 31622}}

In [8]:
import pandas as pd

pricing_requests = []

requests = [r1, r2]
for r in requests:
    pricing_requests.append(
        pd.DataFrame(r.json()['prices']).assign(**r.json()['request'])
    )

pricing_requests = pd.concat(pricing_requests)
pricing_requests.head()

   hotel_id  price  stock   city  date language  mobile  avatar_id
0        62     86      0  paris     2   french       0      30892
1       882    221      0  paris     2   french       0      30892
2       602    115      0  paris     2   french       0      30892
3       447    136      0  paris     2   french       0      30892
4       645    161      0  paris     2   french       0      30892

In [9]:
len(pricing_requests)

310

In [13]:
hotels = pd.read_csv('Desktop/features_hotels.csv', index_col=['hotel_id', 'city'])
pricing_requests = pricing_requests.join(hotels, on=['hotel_id', 'city'])
pricing_requests.head()

,hotel_id,price,stock,city,date,language,mobile,avatar_id,group,brand,parking,pool,children_policy
0,62,86,0,paris,2,french,0,30892,Accar Hotels,Ibas,0,0,0
1,882,221,0,paris,2,french,0,30892,Accar Hotels,Marcure,1,1,0
2,602,115,0,paris,2,french,0,30892,Independant,Independant,1,0,0
3,447,136,0,paris,2,french,0,30892,Accar Hotels,Navatel,1,0,1
4,645,161,0,paris,2,french,0,30892,Boss Western,J.Halliday Inn,1,0,1

In [16]:
pricing_requests.to_csv('Desktop/sample_train.csv', index=False)