In [17]:
import urllib.parse

domain = "51.91.251.0"
port = 3000
host = f"http://{domain}:{port}"
path = lambda x: urllib.parse.urljoin(host, x)

In [18]:
import requests

user_id = '8ad307f1-c2d2-4e02-8647-2fdf40228105'
name = 'avatar1'
r = requests.post(path(f'avatars/{user_id}/{name}'))
r

In [19]:
name = 'avatar2'
r = requests.post(path(f"avatars/{user_id}/{name}"))
r

In [20]:
r = requests.get(path(f"avatars/{user_id}"))
for avatar in r.json():
    print(avatar['id'], avatar['name'])

30892 avatar1
31626 avatar3
31627 avatar4
31622 avatar2

In [22]:
params = {
    "avatar_name": "avatar1",
    "language": "french",
    "city": "paris",
    "date": 1,
    "mobile": 0,
}
r1 = requests.get(path(f"pricing/{user_id}"), params=params)
r1.json()

{'prices': [{'hotel_id': 911, 'price': 153, 'stock': 4},
  {'hotel_id': 970, 'price': 329, 'stock': 1},
  {'hotel_id': 853, 'price': 188, 'stock': 1},
  {'hotel_id': 379, 'price': 431, 'stock': 1},
  {'hotel_id': 663, 'price': 155, 'stock': 3},
  {'hotel_id': 290, 'price': 191, 'stock': 0},
  {'hotel_id': 29, 'price': 319, 'stock': 1},
  {'hotel_id': 436, 'price': 247, 'stock': 15},
  {'hotel_id': 972, 'price': 100, 'stock': 3},
  {'hotel_id': 522, 'price': 196, 'stock': 0},
  {'hotel_id': 467, 'price': 255, 'stock': 43},
  {'hotel_id': 602, 'price': 115, 'stock': 0},
  {'hotel_id': 339, 'price': 253, 'stock': 1},
  {'hotel_id': 342, 'price': 120, 'stock': 0},
  {'hotel_id': 133, 'price': 158, 'stock': 0},
  {'hotel_id': 986, 'price': 322, 'stock': 1},
  {'hotel_id': 392, 'price': 190, 'stock': 0},
  {'hotel_id': 257, 'price': 188, 'stock': 0},
  {'hotel_id': 612, 'price': 227, 'stock': 1},
  {'hotel_id': 359, 'price': 141, 'stock': 0},
  {'hotel_id': 767, 'price': 188, 'stock': 0},
  {'hotel_id': 27, 'price': 355, 'stock': 2},
  {'hotel_id': 579, 'price': 85, 'stock': 0},
  {'hotel_id': 254, 'price': 165, 'stock': 0},
  {'hotel_id': 656, 'price': 150, 'stock': 0},
  {'hotel_id': 640, 'price': 193, 'stock': 0},
  {'hotel_id': 736, 'price': 225, 'stock': 0},
  {'hotel_id': 785, 'price': 284, 'stock': 1},
  {'hotel_id': 992, 'price': 83, 'stock': 0},
  {'hotel_id': 115, 'price': 107, 'stock': 17},
  {'hotel_id': 617, 'price': 449, 'stock': 1},
  {'hotel_id': 858, 'price': 300, 'stock': 1},
  {'hotel_id': 803, 'price': 364, 'stock': 1},
  {'hotel_id': 866, 'price': 457, 'stock': 1},
  {'hotel_id': 797, 'price': 145, 'stock': 0},
  {'hotel_id': 790, 'price': 455, 'stock': 1},
  {'hotel_id': 447, 'price': 136, 'stock': 0},
  {'hotel_id': 748, 'price': 319, 'stock': 1},
  {'hotel_id': 631, 'price': 83, 'stock': 0},
  {'hotel_id': 722, 'price': 193, 'stock': 0},
  {'hotel_id': 629, 'price': 87, 'stock': 0},
  {'hotel_id': 123, 'price': 155, 'stock': 0},
  {'hotel_id': 509, 'price': 89, 'stock': 0},
  {'hotel_id': 975, 'price': 166, 'stock': 3},
  {'hotel_id': 299, 'price': 115, 'stock': 0},
  {'hotel_id': 492, 'price': 117, 'stock': 0},
  {'hotel_id': 823, 'price': 314, 'stock': 1},
  {'hotel_id': 705, 'price': 143, 'stock': 0},
  {'hotel_id': 795, 'price': 166, 'stock': 0},
  {'hotel_id': 199, 'price': 229, 'stock': 0},
  {'hotel_id': 397, 'price': 427, 'stock': 1},
  {'hotel_id': 946, 'price': 324, 'stock': 1},
  {'hotel_id': 216, 'price': 241, 'stock': 3},
  {'hotel_id': 573, 'price': 425, 'stock': 1},
  {'hotel_id': 248, 'price': 314, 'stock': 1},
  {'hotel_id': 308, 'price': 297, 'stock': 1},
  {'hotel_id': 474, 'price': 183, 'stock': 0},
  {'hotel_id': 825, 'price': 188, 'stock': 2},
  {'hotel_id': 882, 'price': 222, 'stock': 0},
  {'hotel_id': 238, 'price': 159, 'stock': 0},
  {'hotel_id': 842, 'price': 443, 'stock': 1},
  {'hotel_id': 176, 'price': 86, 'stock': 0},
  {'hotel_id': 331, 'price': 98, 'stock': 1},
  {'hotel_id': 634, 'price': 87, 'stock': 0},
  {'hotel_id': 647, 'price': 143, 'stock': 0},
  {'hotel_id': 222, 'price': 340, 'stock': 2},
  {'hotel_id': 708, 'price': 188, 'stock': 1},
  {'hotel_id': 207, 'price': 165, 'stock': 0},
  {'hotel_id': 24, 'price': 411, 'stock': 1},
  {'hotel_id': 580, 'price': 141, 'stock': 4},
  {'hotel_id': 182, 'price': 162, 'stock': 0},
  {'hotel_id': 484, 'price': 138, 'stock': 1},
  {'hotel_id': 327, 'price': 227, 'stock': 0},
  {'hotel_id': 577, 'price': 188, 'stock': 0},
  {'hotel_id': 998, 'price': 225, 'stock': 0},
  {'hotel_id': 338, 'price': 196, 'stock': 12},
  {'hotel_id': 94, 'price': 250, 'stock': 38},
  {'hotel_id': 165, 'price': 161, 'stock': 0},
  {'hotel_id': 741, 'price': 190, 'stock': 1},
  {'hotel_id': 980, 'price': 114, 'stock': 0},
  {'hotel_id': 576, 'price': 227, 'stock': 0},
  {'hotel_id': 756, 'price': 247, 'stock': 1},
  {'hotel_id': 851, 'price': 89, 'stock': 0},
  {'hotel_id': 942, 'price': 314, 'stock': 1},
  {'hotel_id': 69, 'price': 252, 'stock': 42},
  {'hotel_id': 782, 'price': 370, 'stock': 2},
  {'hotel_id': 558, 'price': 102, 'stock': 0},
  {'hotel_id': 65, 'price': 161, 'stock': 0},
  {'hotel_id': 121, 'price': 83, 'stock': 0},
  {'hotel_id': 274, 'price': 191, 'stock': 0},
  {'hotel_id': 259, 'price': 138, 'stock': 0},
  {'hotel_id': 837, 'price': 419, 'stock': 1},
  {'hotel_id': 884, 'price': 223, 'stock': 0},
  {'hotel_id': 949, 'price': 395, 'stock': 1},
  {'hotel_id': 449, 'price': 222, 'stock': 1},
  {'hotel_id': 910, 'price': 88, 'stock': 0},
  {'hotel_id': 560, 'price': 186, 'stock': 2},
  {'hotel_id': 227, 'price': 85, 'stock': 0},
  {'hotel_id': 159, 'price': 316, 'stock': 1},
  {'hotel_id': 738, 'price': 143, 'stock': 0},
  {'hotel_id': 225, 'price': 191, 'stock': 0},
  {'hotel_id': 808, 'price': 441, 'stock': 1},
  {'hotel_id': 28, 'price': 199, 'stock': 0},
  {'hotel_id': 723, 'price': 86, 'stock': 0},
  {'hotel_id': 731, 'price': 188, 'stock': 0},
  {'hotel_id': 534, 'price': 400, 'stock': 1},
  {'hotel_id': 66, 'price': 186, 'stock': 0},
  {'hotel_id': 49, 'price': 161, 'stock': 0},
  {'hotel_id': 584, 'price': 462, 'stock': 1},
  {'hotel_id': 14, 'price': 156, 'stock': 0},
  {'hotel_id': 889, 'price': 191, 'stock': 0},
  {'hotel_id': 863, 'price': 457, 'stock': 1},
  {'hotel_id': 229, 'price': 222, 'stock': 1},
  {'hotel_id': 188, 'price': 85, 'stock': 7},
  {'hotel_id': 41, 'price': 136, 'stock': 1},
  {'hotel_id': 595, 'price': 188, 'stock': 0},
  {'hotel_id': 885, 'price': 191, 'stock': 1},
  {'hotel_id': 132, 'price': 449, 'stock': 1},
  {'hotel_id': 948, 'price': 241, 'stock': 1},
  {'hotel_id': 412, 'price': 266, 'stock': 63},
  {'hotel_id': 776, 'price': 159, 'stock': 0},
  {'hotel_id': 419, 'price': 136, 'stock': 1},
  {'hotel_id': 148, 'price': 114, 'stock': 0},
  {'hotel_id': 306, 'price': 227, 'stock': 1},
  {'hotel_id': 645, 'price': 161, 'stock': 0},
  {'hotel_id': 912, 'price': 165, 'stock': 0},
  {'hotel_id': 684, 'price': 85, 'stock': 0},
  {'hotel_id': 734, 'price': 141, 'stock': 0},
  {'hotel_id': 937, 'price': 281, 'stock': 1},
  {'hotel_id': 868, 'price': 287, 'stock': 1},
  {'hotel_id': 792, 'price': 85, 'stock': 2},
  {'hotel_id': 903, 'price': 89, 'stock': 0},
  {'hotel_id': 614, 'price': 88, 'stock': 0},
  {'hotel_id': 130, 'price': 316, 'stock': 1},
  {'hotel_id': 150, 'price': 227, 'stock': 10},
  {'hotel_id': 357, 'price': 188, 'stock': 0},
  {'hotel_id': 926, 'price': 188, 'stock': 8},
  {'hotel_id': 21, 'price': 86, 'stock': 0},
  {'hotel_id': 192, 'price': 119, 'stock': 0},
  {'hotel_id': 817, 'price': 302, 'stock': 1},
  {'hotel_id': 62, 'price': 86, 'stock': 0},
  {'hotel_id': 963, 'price': 136, 'stock': 0},
  {'hotel_id': 314, 'price': 117, 'stock': 0},
  {'hotel_id': 564, 'price': 92, 'stock': 0},
  {'hotel_id': 571, 'price': 457, 'stock': 0},
  {'hotel_id': 735, 'price': 194, 'stock': 0},
  {'hotel_id': 301, 'price': 133, 'stock': 1},
  {'hotel_id': 841, 'price': 87, 'stock': 0},
  {'hotel_id': 599, 'price': 103, 'stock': 12},
  {'hotel_id': 95, 'price': 455, 'stock': 1},
  {'hotel_id': 119, 'price': 316, 'stock': 1},
  {'hotel_id': 700, 'price': 178, 'stock': 55},
  {'hotel_id': 305, 'price': 193, 'stock': 1},
  {'hotel_id': 742, 'price': 418, 'stock': 1},
  {'hotel_id': 477, 'price': 84, 'stock': 0}],
 'request': {'city': 'paris',
  'date': 1,
  'language': 'french',
  'mobile': 0,
  'avatar_id': 30892}}

In [23]:
params = {
    "avatar_name": "avatar2",
    "language": "french",
    "city": "paris",
    "date": 0,
    "mobile": 1,
}
r2 = requests.get(path(f"pricing/{user_id}"), params=params)
r2.json()

{'prices': [{'hotel_id': 972, 'price': 92, 'stock': 3},
  {'hotel_id': 722, 'price': 193, 'stock': 0},
  {'hotel_id': 94, 'price': 230, 'stock': 34},
  {'hotel_id': 290, 'price': 191, 'stock': 0},
  {'hotel_id': 24, 'price': 411, 'stock': 0},
  {'hotel_id': 397, 'price': 427, 'stock': 0},
  {'hotel_id': 580, 'price': 130, 'stock': 4},
  {'hotel_id': 560, 'price': 186, 'stock': 0},
  {'hotel_id': 842, 'price': 443, 'stock': 0},
  {'hotel_id': 735, 'price': 194, 'stock': 0},
  {'hotel_id': 467, 'price': 235, 'stock': 41},
  {'hotel_id': 436, 'price': 228, 'stock': 10},
  {'hotel_id': 803, 'price': 364, 'stock': 0},
  {'hotel_id': 742, 'price': 418, 'stock': 0},
  {'hotel_id': 447, 'price': 136, 'stock': 0},
  {'hotel_id': 576, 'price': 227, 'stock': 0},
  {'hotel_id': 49, 'price': 161, 'stock': 0},
  {'hotel_id': 708, 'price': 188, 'stock': 0},
  {'hotel_id': 837, 'price': 419, 'stock': 0},
  {'hotel_id': 823, 'price': 314, 'stock': 0},
  {'hotel_id': 225, 'price': 191, 'stock': 0},
  {'hotel_id': 790, 'price': 455, 'stock': 0},
  {'hotel_id': 584, 'price': 462, 'stock': 0},
  {'hotel_id': 121, 'price': 83, 'stock': 0},
  {'hotel_id': 889, 'price': 191, 'stock': 0},
  {'hotel_id': 970, 'price': 406, 'stock': 0},
  {'hotel_id': 229, 'price': 222, 'stock': 0},
  {'hotel_id': 412, 'price': 244, 'stock': 61},
  {'hotel_id': 119, 'price': 316, 'stock': 0},
  {'hotel_id': 342, 'price': 120, 'stock': 0},
  {'hotel_id': 640, 'price': 193, 'stock': 0},
  {'hotel_id': 522, 'price': 196, 'stock': 0},
  {'hotel_id': 133, 'price': 158, 'stock': 0},
  {'hotel_id': 259, 'price': 138, 'stock': 0},
  {'hotel_id': 299, 'price': 115, 'stock': 0},
  {'hotel_id': 884, 'price': 223, 'stock': 0},
  {'hotel_id': 62, 'price': 86, 'stock': 0},
  {'hotel_id': 797, 'price': 145, 'stock': 0},
  {'hotel_id': 885, 'price': 191, 'stock': 0},
  {'hotel_id': 115, 'price': 99, 'stock': 16},
  {'hotel_id': 926, 'price': 173, 'stock': 7},
  {'hotel_id': 573, 'price': 425, 'stock': 0},
  {'hotel_id': 29, 'price': 319, 'stock': 0},
  {'hotel_id': 477, 'price': 84, 'stock': 0},
  {'hotel_id': 248, 'price': 314, 'stock': 0},
  {'hotel_id': 222, 'price': 323, 'stock': 1},
  {'hotel_id': 949, 'price': 395, 'stock': 0},
  {'hotel_id': 948, 'price': 297, 'stock': 0},
  {'hotel_id': 564, 'price': 92, 'stock': 0},
  {'hotel_id': 992, 'price': 83, 'stock': 0},
  {'hotel_id': 795, 'price': 166, 'stock': 0},
  {'hotel_id': 851, 'price': 89, 'stock': 0},
  {'hotel_id': 207, 'price': 165, 'stock': 0},
  {'hotel_id': 808, 'price': 441, 'stock': 0},
  {'hotel_id': 663, 'price': 143, 'stock': 2},
  {'hotel_id': 314, 'price': 117, 'stock': 0},
  {'hotel_id': 882, 'price': 222, 'stock': 0},
  {'hotel_id': 21, 'price': 86, 'stock': 0},
  {'hotel_id': 631, 'price': 83, 'stock': 0},
  {'hotel_id': 95, 'price': 455, 'stock': 0},
  {'hotel_id': 736, 'price': 225, 'stock': 0},
  {'hotel_id': 866, 'price': 457, 'stock': 0},
  {'hotel_id': 579, 'price': 85, 'stock': 0},
  {'hotel_id': 176, 'price': 86, 'stock': 0},
  {'hotel_id': 629, 'price': 87, 'stock': 0},
  {'hotel_id': 903, 'price': 89, 'stock': 0},
  {'hotel_id': 534, 'price': 400, 'stock': 0},
  {'hotel_id': 199, 'price': 229, 'stock': 0},
  {'hotel_id': 910, 'price': 88, 'stock': 0},
  {'hotel_id': 767, 'price': 188, 'stock': 0},
  {'hotel_id': 216, 'price': 229, 'stock': 2},
  {'hotel_id': 301, 'price': 133, 'stock': 0},
  {'hotel_id': 66, 'price': 186, 'stock': 0},
  {'hotel_id': 474, 'price': 183, 'stock': 0},
  {'hotel_id': 602, 'price': 115, 'stock': 0},
  {'hotel_id': 254, 'price': 165, 'stock': 0},
  {'hotel_id': 338, 'price': 181, 'stock': 10},
  {'hotel_id': 980, 'price': 114, 'stock': 0},
  {'hotel_id': 492, 'price': 117, 'stock': 0},
  {'hotel_id': 705, 'price': 143, 'stock': 0},
  {'hotel_id': 165, 'price': 161, 'stock': 0},
  {'hotel_id': 306, 'price': 227, 'stock': 0},
  {'hotel_id': 647, 'price': 143, 'stock': 0},
  {'hotel_id': 392, 'price': 190, 'stock': 0},
  {'hotel_id': 449, 'price': 222, 'stock': 0},
  {'hotel_id': 700, 'price': 164, 'stock': 53},
  {'hotel_id': 825, 'price': 173, 'stock': 1},
  {'hotel_id': 558, 'price': 102, 'stock': 0},
  {'hotel_id': 41, 'price': 136, 'stock': 0},
  {'hotel_id': 868, 'price': 287, 'stock': 0},
  {'hotel_id': 331, 'price': 98, 'stock': 0},
  {'hotel_id': 599, 'price': 95, 'stock': 9},
  {'hotel_id': 853, 'price': 188, 'stock': 0},
  {'hotel_id': 946, 'price': 324, 'stock': 0},
  {'hotel_id': 419, 'price': 136, 'stock': 0},
  {'hotel_id': 238, 'price': 159, 'stock': 0},
  {'hotel_id': 975, 'price': 152, 'stock': 2},
  {'hotel_id': 28, 'price': 199, 'stock': 0},
  {'hotel_id': 123, 'price': 155, 'stock': 0},
  {'hotel_id': 227, 'price': 85, 'stock': 0},
  {'hotel_id': 612, 'price': 227, 'stock': 0},
  {'hotel_id': 734, 'price': 141, 'stock': 0},
  {'hotel_id': 942, 'price': 314, 'stock': 0},
  {'hotel_id': 65, 'price': 161, 'stock': 0},
  {'hotel_id': 684, 'price': 85, 'stock': 0},
  {'hotel_id': 782, 'price': 370, 'stock': 0},
  {'hotel_id': 339, 'price': 316, 'stock': 0},
  {'hotel_id': 595, 'price': 188, 'stock': 0},
  {'hotel_id': 308, 'price': 297, 'stock': 0},
  {'hotel_id': 937, 'price': 281, 'stock': 0},
  {'hotel_id': 577, 'price': 188, 'stock': 0},
  {'hotel_id': 14, 'price': 156, 'stock': 0},
  {'hotel_id': 327, 'price': 227, 'stock': 0},
  {'hotel_id': 257, 'price': 188, 'stock': 0},
  {'hotel_id': 614, 'price': 88, 'stock': 0},
  {'hotel_id': 159, 'price': 316, 'stock': 0},
  {'hotel_id': 148, 'price': 114, 'stock': 0},
  {'hotel_id': 863, 'price': 457, 'stock': 0},
  {'hotel_id': 357, 'price': 188, 'stock': 0},
  {'hotel_id': 748, 'price': 319, 'stock': 0},
  {'hotel_id': 792, 'price': 78, 'stock': 2},
  {'hotel_id': 571, 'price': 457, 'stock': 0},
  {'hotel_id': 911, 'price': 146, 'stock': 3},
  {'hotel_id': 617, 'price': 449, 'stock': 0},
  {'hotel_id': 634, 'price': 87, 'stock': 0},
  {'hotel_id': 656, 'price': 150, 'stock': 0},
  {'hotel_id': 776, 'price': 159, 'stock': 0},
  {'hotel_id': 785, 'price': 284, 'stock': 0},
  {'hotel_id': 738, 'price': 143, 'stock': 0},
  {'hotel_id': 359, 'price': 141, 'stock': 0},
  {'hotel_id': 756, 'price': 302, 'stock': 0},
  {'hotel_id': 963, 'price': 136, 'stock': 0},
  {'hotel_id': 132, 'price': 449, 'stock': 0},
  {'hotel_id': 741, 'price': 190, 'stock': 0},
  {'hotel_id': 841, 'price': 87, 'stock': 0},
  {'hotel_id': 69, 'price': 232, 'stock': 38},
  {'hotel_id': 645, 'price': 161, 'stock': 0},
  {'hotel_id': 998, 'price': 225, 'stock': 0},
  {'hotel_id': 509, 'price': 89, 'stock': 0},
  {'hotel_id': 27, 'price': 355, 'stock': 0},
  {'hotel_id': 817, 'price': 302, 'stock': 0},
  {'hotel_id': 858, 'price': 300, 'stock': 0},
  {'hotel_id': 192, 'price': 119, 'stock': 0},
  {'hotel_id': 182, 'price': 162, 'stock': 0},
  {'hotel_id': 150, 'price': 209, 'stock': 9},
  {'hotel_id': 130, 'price': 316, 'stock': 0},
  {'hotel_id': 188, 'price': 78, 'stock': 7},
  {'hotel_id': 274, 'price': 191, 'stock': 0},
  {'hotel_id': 731, 'price': 188, 'stock': 0},
  {'hotel_id': 723, 'price': 86, 'stock': 0},
  {'hotel_id': 484, 'price': 138, 'stock': 0},
  {'hotel_id': 379, 'price': 431, 'stock': 0},
  {'hotel_id': 986, 'price': 322, 'stock': 0},
  {'hotel_id': 305, 'price': 193, 'stock': 0},
  {'hotel_id': 912, 'price': 165, 'stock': 0}],
 'request': {'city': 'paris',
  'date': 0,
  'language': 'french',
  'mobile': 1,
  'avatar_id': 31622}}

In [11]:
import pandas as pd

In [36]:
pricing_requests = []

requests = [r1, r2]
for r in requests:
    pricing_requests.append(
        pd.DataFrame(r.json()['prices']).assign(**r.json()['request'])
    )

pricing_requests = pd.concat(pricing_requests)
pricing_requests.head()

   hotel_id  price  stock   city  date language  mobile  avatar_id
0       911    153      4  paris     1   french       0      30892
1       970    329      1  paris     1   french       0      30892
2       853    188      1  paris     1   french       0      30892
3       379    431      1  paris     1   french       0      30892
4       663    155      3  paris     1   french       0      30892

In [25]:
len(pricing_requests)

310

In [27]:
hotels = pd.read_csv('features_hotels.csv', index_col=['hotel_id', 'city'])
pricing_requests = pricing_requests.join(hotels, on=['hotel_id', 'city'])
pricing_requests.head()

,hotel_id,price,stock,city,date,language,mobile,avatar_id,group,brand,parking,pool,children_policy
0,911,153,4,paris,1,french,0,30892,Boss Western,Boss Western,0,0,0
1,970,329,1,paris,1,french,0,30892,Chillton Worldwide,Chill Garden Inn,0,0,2
2,853,188,1,paris,1,french,0,30892,Chillton Worldwide,Tripletree,1,0,0
3,379,431,1,paris,1,french,0,30892,Morriott International,Corlton,0,0,0
4,663,155,3,paris,1,french,0,30892,Chillton Worldwide,Tripletree,0,0,0

In [28]:
pricing_requests.to_csv('sample_train.csv', index=False)

In [6]:
name = 'avatar3'
r = requests.post(path(f"avatars/{user_id}/{name}"))
r

In [4]:
name = 'avatar4'
r = requests.post(path(f"avatars/{user_id}/{name}"))
r

In [5]:
params = {
    "avatar_name": "avatar4",
    "language": "german",
    "city": "madrid",
    "date": 2,
    "mobile": 0,
}
r3 = requests.get(path(f"pricing/{user_id}"), params=params)
r3.json()

{'prices': [{'hotel_id': 388, 'price': 129, 'stock': 0},
  {'hotel_id': 904, 'price': 115, 'stock': 0},
  {'hotel_id': 108, 'price': 98, 'stock': 0},
  {'hotel_id': 857, 'price': 112, 'stock': 2},
  {'hotel_id': 615, 'price': 111, 'stock': 0},
  {'hotel_id': 606, 'price': 247, 'stock': 0},
  {'hotel_id': 261, 'price': 146, 'stock': 1},
  {'hotel_id': 138, 'price': 70, 'stock': 0},
  {'hotel_id': 561, 'price': 65, 'stock': 4},
  {'hotel_id': 997, 'price': 149, 'stock': 0},
  {'hotel_id': 284, 'price': 152, 'stock': 2},
  {'hotel_id': 737, 'price': 149, 'stock': 10},
  {'hotel_id': 791, 'price': 113, 'stock': 1},
  {'hotel_id': 31, 'price': 112, 'stock': 1},
  {'hotel_id': 439, 'price': 111, 'stock': 0},
  {'hotel_id': 252, 'price': 257, 'stock': 1},
  {'hotel_id': 500, 'price': 69, 'stock': 0},
  {'hotel_id': 147, 'price': 177, 'stock': 0},
  {'hotel_id': 246, 'price': 366, 'stock': 2},
  {'hotel_id': 154, 'price': 334, 'stock': 2},
  {'hotel_id': 538, 'price': 126, 'stock': 0},
  {'hotel_id': 276, 'price': 71, 'stock': 0},
  {'hotel_id': 277, 'price': 219, 'stock': 5},
  {'hotel_id': 120, 'price': 155, 'stock': 1},
  {'hotel_id': 427, 'price': 257, 'stock': 1},
  {'hotel_id': 414, 'price': 67, 'stock': 0},
  {'hotel_id': 729, 'price': 345, 'stock': 2},
  {'hotel_id': 175, 'price': 112, 'stock': 0},
  {'hotel_id': 444, 'price': 143, 'stock': 2},
  {'hotel_id': 798, 'price': 359, 'stock': 1},
  {'hotel_id': 499, 'price': 251, 'stock': 1},
  {'hotel_id': 575, 'price': 90, 'stock': 20},
  {'hotel_id': 483, 'price': 96, 'stock': 0},
  {'hotel_id': 126, 'price': 100, 'stock': 1},
  {'hotel_id': 135, 'price': 355, 'stock': 2},
  {'hotel_id': 527, 'price': 150, 'stock': 0},
  {'hotel_id': 378, 'price': 130, 'stock': 0},
  {'hotel_id': 54, 'price': 92, 'stock': 0},
  {'hotel_id': 185, 'price': 150, 'stock': 0},
  {'hotel_id': 310, 'price': 67, 'stock': 0},
  {'hotel_id': 828, 'price': 118, 'stock': 2},
  {'hotel_id': 235, 'price': 153, 'stock': 2},
  {'hotel_id': 313, 'price': 70, 'stock': 0},
  {'hotel_id': 525, 'price': 136, 'stock': 1},
  {'hotel_id': 901, 'price': 363, 'stock': 2},
  {'hotel_id': 966, 'price': 81, 'stock': 1},
  {'hotel_id': 241, 'price': 129, 'stock': 0},
  {'hotel_id': 717, 'price': 366, 'stock': 2},
  {'hotel_id': 2, 'price': 94, 'stock': 0},
  {'hotel_id': 186, 'price': 132, 'stock': 0},
  {'hotel_id': 174, 'price': 133, 'stock': 6},
  {'hotel_id': 384, 'price': 183, 'stock': 2},
  {'hotel_id': 312, 'price': 113, 'stock': 0},
  {'hotel_id': 697, 'price': 152, 'stock': 2},
  {'hotel_id': 398, 'price': 66, 'stock': 1},
  {'hotel_id': 847, 'price': 86, 'stock': 6},
  {'hotel_id': 873, 'price': 221, 'stock': 6},
  {'hotel_id': 733, 'price': 151, 'stock': 1},
  {'hotel_id': 886, 'price': 164, 'stock': 1},
  {'hotel_id': 870, 'price': 73, 'stock': 0},
  {'hotel_id': 860, 'price': 150, 'stock': 2},
  {'hotel_id': 413, 'price': 265, 'stock': 4},
  {'hotel_id': 20, 'price': 73, 'stock': 0},
  {'hotel_id': 7, 'price': 96, 'stock': 0},
  {'hotel_id': 478, 'price': 113, 'stock': 1},
  {'hotel_id': 67, 'price': 204, 'stock': 14},
  {'hotel_id': 721, 'price': 70, 'stock': 0},
  {'hotel_id': 982, 'price': 238, 'stock': 1},
  {'hotel_id': 93, 'price': 266, 'stock': 4},
  {'hotel_id': 102, 'price': 341, 'stock': 2},
  {'hotel_id': 127, 'price': 71, 'stock': 0},
  {'hotel_id': 768, 'price': 372, 'stock': 2},
  {'hotel_id': 618, 'price': 112, 'stock': 0},
  {'hotel_id': 619, 'price': 126, 'stock': 0},
  {'hotel_id': 97, 'price': 234, 'stock': 4},
  {'hotel_id': 39, 'price': 112, 'stock': 1},
  {'hotel_id': 964, 'price': 152, 'stock': 0},
  {'hotel_id': 936, 'price': 152, 'stock': 1},
  {'hotel_id': 780, 'price': 355, 'stock': 2},
  {'hotel_id': 458, 'price': 81, 'stock': 2},
  {'hotel_id': 285, 'price': 93, 'stock': 0},
  {'hotel_id': 75, 'price': 146, 'stock': 1},
  {'hotel_id': 600, 'price': 65, 'stock': 0},
  {'hotel_id': 888, 'price': 219, 'stock': 14},
  {'hotel_id': 297, 'price': 357, 'stock': 2},
  {'hotel_id': 941, 'price': 69, 'stock': 0},
  {'hotel_id': 233, 'price': 153, 'stock': 0},
  {'hotel_id': 822, 'price': 191, 'stock': 2},
  {'hotel_id': 633, 'price': 152, 'stock': 2},
  {'hotel_id': 205, 'price': 90, 'stock': 0},
  {'hotel_id': 747, 'price': 180, 'stock': 3},
  {'hotel_id': 800, 'price': 95, 'stock': 0},
  {'hotel_id': 164, 'price': 149, 'stock': 2},
  {'hotel_id': 468, 'price': 68, 'stock': 0},
  {'hotel_id': 351, 'price': 95, 'stock': 1},
  {'hotel_id': 333, 'price': 107, 'stock': 2},
  {'hotel_id': 789, 'price': 78, 'stock': 0},
  {'hotel_id': 909, 'price': 68, 'stock': 0},
  {'hotel_id': 845, 'price': 328, 'stock': 2},
  {'hotel_id': 495, 'price': 353, 'stock': 2},
  {'hotel_id': 939, 'price': 174, 'stock': 0},
  {'hotel_id': 689, 'price': 90, 'stock': 0},
  {'hotel_id': 411, 'price': 95, 'stock': 0},
  {'hotel_id': 393, 'price': 152, 'stock': 2},
  {'hotel_id': 79, 'price': 116, 'stock': 1},
  {'hotel_id': 322, 'price': 84, 'stock': 3},
  {'hotel_id': 149, 'price': 182, 'stock': 0}],
 'request': {'city': 'madrid',
  'date': 2,
  'language': 'german',
  'mobile': 0,
  'avatar_id': 31627}}

In [8]:
params = {
    "avatar_name": "avatar3",
    "language": "polish",
    "city": "madrid",
    "date": 2,
    "mobile": 0,
}
r4 = requests.get(path(f"pricing/{user_id}"), params=params)
r4.json()

{'prices': [{'hotel_id': 615, 'price': 113, 'stock': 0},
  {'hotel_id': 388, 'price': 131, 'stock': 0},
  {'hotel_id': 261, 'price': 148, 'stock': 1},
  {'hotel_id': 54, 'price': 93, 'stock': 0},
  {'hotel_id': 618, 'price': 114, 'stock': 0},
  {'hotel_id': 500, 'price': 70, 'stock': 0},
  {'hotel_id': 499, 'price': 256, 'stock': 1},
  {'hotel_id': 941, 'price': 70, 'stock': 0},
  {'hotel_id': 241, 'price': 131, 'stock': 0},
  {'hotel_id': 310, 'price': 68, 'stock': 0},
  {'hotel_id': 97, 'price': 238, 'stock': 4},
  {'hotel_id': 277, 'price': 223, 'stock': 5},
  {'hotel_id': 39, 'price': 114, 'stock': 1},
  {'hotel_id': 997, 'price': 152, 'stock': 0},
  {'hotel_id': 427, 'price': 262, 'stock': 1},
  {'hotel_id': 909, 'price': 69, 'stock': 0},
  {'hotel_id': 619, 'price': 128, 'stock': 0},
  {'hotel_id': 483, 'price': 98, 'stock': 0},
  {'hotel_id': 138, 'price': 71, 'stock': 0},
  {'hotel_id': 108, 'price': 100, 'stock': 0},
  {'hotel_id': 478, 'price': 115, 'stock': 1},
  {'hotel_id': 120, 'price': 158, 'stock': 1},
  {'hotel_id': 186, 'price': 134, 'stock': 0},
  {'hotel_id': 538, 'price': 128, 'stock': 0},
  {'hotel_id': 495, 'price': 360, 'stock': 2},
  {'hotel_id': 246, 'price': 373, 'stock': 2},
  {'hotel_id': 689, 'price': 91, 'stock': 0},
  {'hotel_id': 600, 'price': 66, 'stock': 0},
  {'hotel_id': 780, 'price': 362, 'stock': 2},
  {'hotel_id': 233, 'price': 156, 'stock': 0},
  {'hotel_id': 789, 'price': 79, 'stock': 0},
  {'hotel_id': 633, 'price': 155, 'stock': 2},
  {'hotel_id': 964, 'price': 155, 'stock': 0},
  {'hotel_id': 828, 'price': 120, 'stock': 2},
  {'hotel_id': 147, 'price': 181, 'stock': 0},
  {'hotel_id': 860, 'price': 153, 'stock': 2},
  {'hotel_id': 798, 'price': 366, 'stock': 1},
  {'hotel_id': 67, 'price': 208, 'stock': 14},
  {'hotel_id': 20, 'price': 74, 'stock': 0},
  {'hotel_id': 606, 'price': 251, 'stock': 0},
  {'hotel_id': 873, 'price': 225, 'stock': 6},
  {'hotel_id': 135, 'price': 362, 'stock': 2},
  {'hotel_id': 697, 'price': 155, 'stock': 2},
  {'hotel_id': 93, 'price': 271, 'stock': 4},
  {'hotel_id': 252, 'price': 262, 'stock': 1},
  {'hotel_id': 398, 'price': 67, 'stock': 1},
  {'hotel_id': 791, 'price': 115, 'stock': 1},
  {'hotel_id': 175, 'price': 114, 'stock': 0},
  {'hotel_id': 333, 'price': 109, 'stock': 2},
  {'hotel_id': 164, 'price': 152, 'stock': 2},
  {'hotel_id': 384, 'price': 186, 'stock': 2},
  {'hotel_id': 413, 'price': 270, 'stock': 4},
  {'hotel_id': 888, 'price': 223, 'stock': 14},
  {'hotel_id': 313, 'price': 71, 'stock': 0},
  {'hotel_id': 458, 'price': 83, 'stock': 2},
  {'hotel_id': 414, 'price': 68, 'stock': 0},
  {'hotel_id': 747, 'price': 183, 'stock': 3},
  {'hotel_id': 411, 'price': 97, 'stock': 0},
  {'hotel_id': 79, 'price': 118, 'stock': 1},
  {'hotel_id': 2, 'price': 96, 'stock': 0},
  {'hotel_id': 561, 'price': 66, 'stock': 4},
  {'hotel_id': 822, 'price': 195, 'stock': 2},
  {'hotel_id': 351, 'price': 97, 'stock': 1},
  {'hotel_id': 733, 'price': 154, 'stock': 1},
  {'hotel_id': 312, 'price': 115, 'stock': 0},
  {'hotel_id': 966, 'price': 83, 'stock': 1},
  {'hotel_id': 285, 'price': 95, 'stock': 0},
  {'hotel_id': 322, 'price': 86, 'stock': 3},
  {'hotel_id': 717, 'price': 373, 'stock': 2},
  {'hotel_id': 439, 'price': 113, 'stock': 0},
  {'hotel_id': 284, 'price': 155, 'stock': 2},
  {'hotel_id': 126, 'price': 102, 'stock': 1},
  {'hotel_id': 174, 'price': 135, 'stock': 6},
  {'hotel_id': 154, 'price': 340, 'stock': 2},
  {'hotel_id': 721, 'price': 71, 'stock': 0},
  {'hotel_id': 800, 'price': 97, 'stock': 0},
  {'hotel_id': 527, 'price': 153, 'stock': 0},
  {'hotel_id': 393, 'price': 155, 'stock': 2},
  {'hotel_id': 102, 'price': 348, 'stock': 2},
  {'hotel_id': 575, 'price': 91, 'stock': 20},
  {'hotel_id': 7, 'price': 98, 'stock': 0},
  {'hotel_id': 870, 'price': 74, 'stock': 0},
  {'hotel_id': 768, 'price': 379, 'stock': 2},
  {'hotel_id': 297, 'price': 364, 'stock': 2},
  {'hotel_id': 886, 'price': 167, 'stock': 1},
  {'hotel_id': 901, 'price': 370, 'stock': 2},
  {'hotel_id': 185, 'price': 153, 'stock': 0},
  {'hotel_id': 31, 'price': 114, 'stock': 1},
  {'hotel_id': 936, 'price': 155, 'stock': 1},
  {'hotel_id': 127, 'price': 72, 'stock': 0},
  {'hotel_id': 468, 'price': 69, 'stock': 0},
  {'hotel_id': 845, 'price': 335, 'stock': 2},
  {'hotel_id': 847, 'price': 88, 'stock': 6},
  {'hotel_id': 149, 'price': 185, 'stock': 0},
  {'hotel_id': 444, 'price': 146, 'stock': 2},
  {'hotel_id': 525, 'price': 139, 'stock': 1},
  {'hotel_id': 276, 'price': 73, 'stock': 0},
  {'hotel_id': 982, 'price': 243, 'stock': 1},
  {'hotel_id': 857, 'price': 114, 'stock': 2},
  {'hotel_id': 904, 'price': 117, 'stock': 0},
  {'hotel_id': 737, 'price': 152, 'stock': 10},
  {'hotel_id': 378, 'price': 132, 'stock': 0},
  {'hotel_id': 205, 'price': 91, 'stock': 0},
  {'hotel_id': 939, 'price': 178, 'stock': 0},
  {'hotel_id': 729, 'price': 352, 'stock': 2},
  {'hotel_id': 75, 'price': 148, 'stock': 1},
  {'hotel_id': 235, 'price': 156, 'stock': 2}],
 'request': {'city': 'madrid',
  'date': 2,
  'language': 'polish',
  'mobile': 0,
  'avatar_id': 31626}}

In [40]:
pricing_requests2 = []
requests = [r3, r4]
for r in requests:
    pricing_requests2.append(
        pd.DataFrame(r.json()['prices']).assign(**r.json()['request'])
    )

In [41]:
pricing_requests2 = pd.concat(pricing_requests2)

In [42]:
len(pricing_requests2)

214

In [44]:
hotels = pd.read_csv('features_hotels.csv', index_col=['hotel_id', 'city'])
pricing_requests2 = pricing_requests2.join(hotels, on=['hotel_id', 'city'])

In [45]:
pricing_requests2.head()

,hotel_id,price,stock,city,date,language,mobile,avatar_id,group,brand,parking,pool,children_policy
0,721,70,0,madrid,2,german,0,31626,Independant,Independant,0,0,0
1,7,96,0,madrid,2,german,0,31626,Independant,Independant,0,0,0
2,901,363,2,madrid,2,german,0,31626,Morriott International,Corlton,1,1,0
3,600,64,0,madrid,2,german,0,31626,Independant,Independant,1,0,0
4,75,145,1,madrid,2,german,0,31626,Boss Western,Boss Western,0,0,0

In [46]:
pricing_requests3 = pd.concat(pricing_requests, pricing_requests2)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"